#!/bin/bash

set -e
set -o pipefail

SCRIPTS="$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)"

source "${SCRIPTS}/layout.sh"

function usage () {
    printf 'usage: %s publisher collection version\n' "$(basename "$0")"
    echo ''
    echo 'Print license filename for collection version'
}

[ $# -ne 3 ] && usage >&2 && exit 2

PUBLISHER="$1"
COLLECTION="$2"
VERSION="$3"

cd "${SCRIPTS}/.."

# find and print only the most specific license file
while read CANDIDATE; do
    [ -f "$CANDIDATE" ] && echo "$CANDIDATE" && exit 0
done <<EOF
$(collection-root "$PUBLISHER" "$COLLECTION" "$VERSION")/LICENSE
${PUBLISHER}/LICENSE
LICENSE
EOF

echo no license found for $PUBLISHER collection $COLLECTION version $VERSION >&2
exit 1
