#!/bin/bash

set -e
set -o pipefail

source "$(dirname "$0")/layout.sh"

function usage () {
    printf 'usage: %s publisher collection\n' "$(basename "$0")"
    echo ''
    echo 'Print versions of collection'
}

[ $# -ne 2 ] && usage >&2 && exit 2

PUBLISHER="$1"
COLLECTION="$2"

cd "$(dirname "$0")"/..

find "${PUBLISHER}" -maxdepth 1 -type d -name "${COLLECTION}@*" -printf '%f\n' |
version-from-dirname | sort | uniq
