#!/bin/bash

set -e
set -o pipefail

source "$(dirname "$0")/layout.sh"

function usage () {
    printf 'usage: %s publisher\n' "$(basename "$0")"
    echo ''
    echo 'Print collections of publisher'
}

[ $# -ne 1 ] && usage >&2 && exit 2

PUBLISHER="$1"

cd "$(dirname "$0")"/..

find "${PUBLISHER}" -maxdepth 1 -type d -printf '%f\n' |
collection-from-dirname | sort | uniq
